version: '3'
services:
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"

  rabbitmq:
    image:  woov/rabbitmq-delayed-message-exchange
    ports:
      - "15672:15672"
      - "5672:5672"